### ISSUE TITLE
Unable to cast object exception

### ISSUE THREAD

**Issue by trnqllty** [SpeedCAD/SCADtools.Revit.UI.ProgressMeter#1]
![Adsız](https://github.com/SpeedCAD/SCADtools.Revit.UI.ProgressMeter/assets/25572806/ad788499-7403-4c17-ac69-f1cef3e3bf2d)

Hi,
using your dll throws this exception. How can I solve this?
thanks in advance..

**Comment by SpeedCAD** [comment]
Hi,

Can you share some of your code to reproduce the issue myself?.

Anyway, I've just released a new update where an issue has been fixed when users deactivated the status bar through the:<br> View->User Interface tab. Please update to verify if this resolves the problem!

**Comment by trnqllty** [comment]
Hi,
It seems the updated dll solves the problem.
Thank you for quick response..

**Comment by SpeedCAD** [comment]
You're welcome,
I'm glad to hear that the updated DLL resolved the issue for you!
